"""Write ``viz/basemap.js``: the two shores of the channel, in lat/lon.

Issue #131. The viewer's field draws the belief over a flat dark rectangle,
so the strait reads as a schematic rather than as a place. The fix is a
basemap under the field — and the one thing a basemap has to be is
*registered*, because a coastline visibly offset from the water cells is
worse than no coastline at all.

**Why this is vectors and not a raster.** A raster of Bellot Strait means
imagery, and imagery means a licence we would have to establish and a file we
would have to georeference by hand against
:data:`~whiteout.belief.geometry.DEFAULT_STRAIT`. The ticket names shore
polygons as the acceptable substitute, and they buy the registration for
free: the polyline this script writes *is* the ribbon the belief grid masks
its water with, sampled finely, so the land edge cannot drift from the water
cells — the two are the same numbers.

**Why it is generated and committed rather than computed in the page.** The
viewer has no Python, and the land has to be there before a belief frame
arrives (and in an episode that carries none at all). So the shores are
written out once, here, and ``viz/basemap.js`` is the record. It is a
classic script that assigns one global, not JSON behind a ``fetch``, because
``viz/index.html`` opens from ``file://`` where a fetch of a sibling file
fails CORS and a ``<script src>`` does not.

``tests/test_viz_basemap.py`` regenerates the shores and fails if the
committed file has drifted from the geometry, and checks that each shore
point sits on the water boundary rather than near it.

Run it after changing ``DEFAULT_STRAIT``::

    python scripts/make_basemap.py
"""

from __future__ import annotations

import json
from pathlib import Path

from whiteout.belief.geometry import DEFAULT_STRAIT, ChannelPoint, StraitGeometry

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "viz" / "basemap.js"

#: Metres between samples along the centreline. The default ribbon turns about
#: 1 degree over its whole 6.3 km, so 50 m is far finer than the shape needs;
#: it is chosen against the *screen* instead. At the demo viewport the field
#: shows roughly 7 km across ~880 px, so 50 m is about 6 px — short enough
#: that the polyline reads as a curve and not as a chain of chords, and still
#: only ~127 points a shore.
SAMPLE_STEP_M = 50.0

#: What the shoreline is, said where a reader of the page will meet it. The
#: viewer draws this under the field and nothing else attributes it, so it is
#: the credit line as well as the caveat: these shores are a parameterisation
#: of ARENA.md, not a survey and not licensed imagery.
CREDIT = "shoreline: modelled channel, ARENA.md §2 — not a survey"


def sample_shores(
    strait: StraitGeometry, step_m: float = SAMPLE_STEP_M
) -> dict[str, list[list[float]]]:
    """``{"left": [[lat, lon], ...], "right": [...]}`` along the channel's edge.

    ``left`` and ``right`` are the geometry's own sign convention — left of the
    direction of travel is ``w`` positive — and not "north" and "south", which
    would be a fact about this particular polyline rather than about any.

    Each point is :meth:`~whiteout.belief.geometry.StraitGeometry.to_position`
    of ``(s, ±half_width_at(s))``: the boundary
    :meth:`~whiteout.belief.geometry.StraitGeometry.is_water` tests against,
    evaluated at the same arc lengths.
    """
    length = strait.length_m
    count = max(2, int(round(length / step_m)) + 1)
    left: list[list[float]] = []
    right: list[list[float]] = []
    for index in range(count):
        s_m = length * index / (count - 1)
        half = strait.half_width_at(s_m)
        for side, sign in ((left, 1.0), (right, -1.0)):
            lat, lon = strait.to_position(ChannelPoint(s_m=s_m, w_m=sign * half))
            side.append([round(lat, 7), round(lon, 7)])
    return {"left": left, "right": right}


def render(shores: dict[str, list[list[float]]]) -> str:
    """The committed file's text: a classic script assigning one global."""
    payload = {
        "credit": CREDIT,
        "source": "whiteout.belief.geometry.DEFAULT_STRAIT",
        "generator": "scripts/make_basemap.py",
        "sample_step_m": SAMPLE_STEP_M,
        "shores": shores,
    }
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    return (
        "/* basemap.js - the channel's two shores, in lat/lon (WGS-84).\n"
        " *\n"
        " * GENERATED by scripts/make_basemap.py from\n"
        " * whiteout.belief.geometry.DEFAULT_STRAIT. Do not edit by hand: run\n"
        " * the script. tests/test_viz_basemap.py fails when the two disagree.\n"
        " *\n"
        " * The viewer fills everything outside this ribbon as land. It is the\n"
        " * same boundary the belief grid masks its water with, which is the\n"
        " * whole point - the coastline cannot drift from the water cells.\n"
        " */\n"
        "window.WHITEOUT_BASEMAP = " + body + ";\n"
    )


def main() -> None:
    OUTPUT.write_text(render(sample_shores(DEFAULT_STRAIT)), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT).as_posix()}")


if __name__ == "__main__":
    main()
